apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-pv.fullname" . }}
  labels:
{{ include "hello-pv.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hello-pv.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hello-pv.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: "{{ .Chart.Name }}-storage"
          persistentVolumeClaim:
            claimName: "{{ .Chart.Name }}-claim"
      containers:
        - name: {{ .Chart.Name }}
          image: nginx
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: "{{ .Chart.Name }}-storage"

