apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pvName }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/data/{{ .Values.pvName }}/"
