apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-pv.fullname" . }}
  labels:
{{ include "hello-pv.labels" . | indent 4 }}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "hello-pv.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
